services:
  microwarp:
    image: ghcr.io/ccbkkb/microwarp:latest
    container_name: microwarp
    restart: unless-stopped
    ports:
      - "${BIND_PORT}:${BIND_PORT}"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - .env
    volumes:
      - microwarp:/etc/wireguard
    networks:
      - microwarp
      - apinetwork
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          memory: 256M

volumes:
  microwarp:

networks:
  microwarp:
    name: microwarp
  apinetwork:
    name: apinetwork
